SOURCE=*.java
compiler=javac
output=*.class
classfile=BinarySearch.class
exefile=BinarySearch
interpretator=java

compile: $(SOURCE)
	$(compiler) $(SOURCE)
clean: $(output)
	rm -f $(output)
run: $(classfile)
	$(interpretator) $(exefile)


